# Generated by Django 5.2.7 on 2025-10-13 14:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galaxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name="Celestial body's name")),
                ('mass', models.FloatField(blank=True, null=True, verbose_name="Body's mass")),
                ('radius', models.FloatField(blank=True, null=True, verbose_name="Body's radius")),
                ('description', models.TextField(blank=True, verbose_name="Celestial body's description")),
                ('type', models.CharField(max_length=255, verbose_name="Galaxy's type")),
                ('distanceMly', models.FloatField(verbose_name='Distance in millions light-years')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('user', 'User'), ('astronomer', 'Astronomer'), ('admin', 'Administrator')], default='user', max_length=60, verbose_name="User's role")),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'custom_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name="Celestial body's name")),
                ('mass', models.FloatField(blank=True, null=True, verbose_name="Body's mass")),
                ('radius', models.FloatField(blank=True, null=True, verbose_name="Body's radius")),
                ('description', models.TextField(blank=True, verbose_name="Celestial body's description")),
                ('starType', models.CharField(max_length=255, verbose_name="Star's type")),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name="Star's surface temperature")),
                ('luminosity', models.FloatField(blank=True, null=True, verbose_name="Star's luminosity")),
                ('galaxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='app.galaxy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name="Celestial body's name")),
                ('mass', models.FloatField(blank=True, null=True, verbose_name="Body's mass")),
                ('radius', models.FloatField(blank=True, null=True, verbose_name="Body's radius")),
                ('description', models.TextField(blank=True, verbose_name="Celestial body's description")),
                ('habitable', models.BooleanField(default=False, verbose_name="Planet has or hasn't habitable conditions")),
                ('orbitPeriod', models.FloatField(blank=True, null=True, verbose_name='Orbital period in Earth years')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Planets', to='app.star')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
