# Generated by Django 5.2.7 on 2025-10-09 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galaxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Galaxy's name")),
                ('type', models.CharField(max_length=255, verbose_name="Galaxy's type")),
                ('distance_mly', models.FloatField(verbose_name='Distance in millions light-years')),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Star's name")),
                ('starType', models.CharField(max_length=255, verbose_name="Star's type")),
                ('magnitude', models.FloatField(verbose_name="Star's magnitude value")),
                ('galaxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Stars', to='app.galaxy')),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('has_life', models.BooleanField(default=False, verbose_name="Planet has or hasn't life")),
                ('orbit_period', models.FloatField(verbose_name='Orbit period in Earth years')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Planets', to='app.star')),
            ],
        ),
    ]
