# Generated by Django 5.2.7 on 2025-10-16 17:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galaxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name="Celestial body's name")),
                ('mass', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name="Body's mass")),
                ('radius', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name="Body's radius")),
                ('description', models.TextField(blank=True, verbose_name="Celestial body's description")),
                ('discoveryDate', models.DateField(blank=True, null=True, verbose_name='Discovery date')),
                ('discoveredBy', models.CharField(blank=True, max_length=255, verbose_name="Discover's name")),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('verified', models.BooleanField(default=False, verbose_name='Data verified by an astronomer')),
                ('type', models.CharField(choices=[('spiral', 'Spiral'), ('elliptical', 'Elliptical'), ('irregular', 'Irregular')], max_length=255, verbose_name="Galaxy's type")),
                ('distanceMly', models.FloatField(verbose_name='Distance in millions light-years')),
                ('image', models.ImageField(blank=True, null=True, upload_to='galaxyImages/', verbose_name="Galaxy's image")),
            ],
            options={
                'verbose_name_plural': 'Celestial Bodies',
                'ordering': ['-discoveryDate'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('type', models.CharField(blank=True, choices=[('user', 'User'), ('astronomer', 'Astronomer'), ('admin', 'Administrator')], default='user', max_length=60, null=True, verbose_name="User's type")),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profilePics/', verbose_name='Profile picture')),
                ('bio', models.TextField(blank=True, verbose_name="User's biography")),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'customUser',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name="Body's mass")),
                ('radius', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name="Body's radius")),
                ('description', models.TextField(blank=True, verbose_name="Celestial body's description")),
                ('discoveryDate', models.DateField(blank=True, null=True, verbose_name='Discovery date')),
                ('discoveredBy', models.CharField(blank=True, max_length=255, verbose_name="Discover's name")),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('verified', models.BooleanField(default=False, verbose_name='Data verified by an astronomer')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name="Star's name")),
                ('objectId', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('main_sequence', 'Main Sequence'), ('giant', 'Giant'), ('dwarf', 'Dwarf'), ('supergiant', 'Supergiant')], max_length=255, verbose_name="Star's type")),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name="Star's surface temperature")),
                ('luminosity', models.FloatField(blank=True, null=True, verbose_name="Star's luminosity")),
                ('image', models.ImageField(blank=True, null=True, upload_to='starImages/', verbose_name="Star's image")),
                ('contentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'Celestial Bodies',
                'ordering': ['-discoveryDate'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('galaxy', 'Galaxy'), ('star', 'Star'), ('planet', 'Planet'), ('moon', 'Moon'), ('asteroid', 'Asteroid'), ('comet', 'Comet'), ('black_hole', 'Black Hole'), ('nebula', 'Nebula'), ('cluster', 'Cluster'), ('other', 'Other')], max_length=255, verbose_name="Celestial body's type")),
                ('mass', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name="Body's mass")),
                ('radius', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name="Body's radius")),
                ('description', models.TextField(blank=True, verbose_name="Celestial body's description")),
                ('discoveryDate', models.DateField(blank=True, null=True, verbose_name='Discovery date')),
                ('discoveredBy', models.CharField(blank=True, max_length=255, verbose_name="Discover's name")),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('verified', models.BooleanField(default=False, verbose_name='Data verified by an astronomer')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name="Planet's name")),
                ('habitable', models.BooleanField(default=False, verbose_name='Planet has habitable conditions')),
                ('orbitPeriod', models.FloatField(blank=True, null=True, verbose_name='Orbital period in earth years')),
                ('image', models.ImageField(blank=True, null=True, upload_to='planetImages/', verbose_name="Planet's image")),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planets', to='app.star')),
            ],
            options={
                'verbose_name_plural': 'Celestial Bodies',
                'ordering': ['-discoveryDate'],
                'abstract': False,
            },
        ),
    ]
