# Generated by Django 5.2.7 on 2025-10-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_picture',
            new_name='profilePicture',
        ),
        migrations.RenameField(
            model_name='star',
            old_name='contentType',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='star',
            old_name='objectId',
            new_name='object_id',
        ),
    ]
