# Generated by Django 5.2.7 on 2025-10-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_profile_picture_customuser_profilepicture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Astronomer verification status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('astronomer', 'Astronomer')], default='user', max_length=60, null=True, verbose_name="User's type"),
        ),
    ]
