# Generated by Django 5.2.7 on 2025-10-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customuser_verified_alter_customuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name="Celestial body's name"),
        ),
        migrations.AlterField(
            model_name='star',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name="Celestial body's name"),
        ),
    ]
