# Generated by Django 5.2.7 on 2025-10-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_planet_name_alter_star_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galaxy',
            name='type',
            field=models.CharField(choices=[('spiral', 'Spiral'), ('elliptical', 'Elliptical'), ('irregular', 'Irregular')], default='spiral', max_length=255, verbose_name="Galaxy's type"),
        ),
    ]
