# Generated by Django 5.2.7 on 2025-10-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_galaxy_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'CustomUser', 'verbose_name_plural': 'CustomUsers'},
        ),
        migrations.AlterModelOptions(
            name='galaxy',
            options={'verbose_name': 'Galaxy', 'verbose_name_plural': 'Galaxies'},
        ),
        migrations.AlterModelOptions(
            name='planet',
            options={'verbose_name': 'Planet', 'verbose_name_plural': 'Planets'},
        ),
        migrations.AlterModelOptions(
            name='star',
            options={'verbose_name': 'Star', 'verbose_name_plural': 'Stars'},
        ),
        migrations.RenameField(
            model_name='star',
            old_name='content_type',
            new_name='contentType',
        ),
        migrations.RenameField(
            model_name='star',
            old_name='object_id',
            new_name='objectId',
        ),
        migrations.AddField(
            model_name='galaxy',
            name='galaxyType',
            field=models.CharField(choices=[('spiral', 'Spiral'), ('elliptical', 'Elliptical'), ('irregular', 'Irregular')], default='spiral', max_length=255, verbose_name="Galaxy's type"),
        ),
        migrations.AddField(
            model_name='star',
            name='starType',
            field=models.CharField(choices=[('main sequence', 'Main Sequence'), ('giant', 'Giant'), ('dwarf', 'Dwarf'), ('supergiant', 'Supergiant')], default='main sequence', max_length=255, verbose_name="Star's type"),
        ),
        migrations.AlterField(
            model_name='galaxy',
            name='type',
            field=models.CharField(choices=[('galaxy', 'Galaxy'), ('star', 'Star'), ('planet', 'Planet'), ('moon', 'Moon'), ('asteroid', 'Asteroid'), ('comet', 'Comet'), ('black_hole', 'Black Hole'), ('nebula', 'Nebula'), ('cluster', 'Cluster'), ('other', 'Other')], max_length=255, verbose_name="Celestial body's type"),
        ),
        migrations.AlterField(
            model_name='star',
            name='type',
            field=models.CharField(choices=[('galaxy', 'Galaxy'), ('star', 'Star'), ('planet', 'Planet'), ('moon', 'Moon'), ('asteroid', 'Asteroid'), ('comet', 'Comet'), ('black_hole', 'Black Hole'), ('nebula', 'Nebula'), ('cluster', 'Cluster'), ('other', 'Other')], max_length=255, verbose_name="Celestial body's type"),
        ),
    ]
