# Generated by Django 5.2.7 on 2025-10-23 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_customuser_options_alter_galaxy_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='contentType',
        ),
        migrations.RemoveField(
            model_name='star',
            name='objectId',
        ),
        migrations.AddField(
            model_name='star',
            name='galaxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='app.galaxy', verbose_name="star's Galaxy"),
        ),
    ]
